name: 'Tests-strip-loader'

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - CHNAGELOG.md
      - preset
      - .vscode
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os != 'windows-latest' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        node-version:
          - 16
        include:
          - node-version: 14
            os: ubuntu-latest
          - node-version: 18
            os: ubuntu-latest
        webpack-version: [latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
